### ISSUE TITLE
missing mutators from Nexuiz

### ISSUE THREAD

**Issue by YevheniiPokhvalii** [kasymovga/rexuiz#21]
I personally miss weapon mutators. However, there were other cool things. For example, it'd like to play a rocket launcher arena with a vampire mutator. How to do this in Rexuiz?
Here is the Nexuiz mutator roster:
![nexuiz000005](https://user-images.githubusercontent.com/68227075/226186891-215f717d-5704-4bf6-8ca4-893a8b85360b.jpg)
Here is the roster from Xonotic:
![xonotic20230319175322-00](https://user-images.githubusercontent.com/68227075/226188015-9094d0e6-08d2-4489-a5ac-4cc78f905f1c.jpg)

**Comment by YevheniiPokhvalii** [comment]
Also, please add all possible physics as mutators. Not only cpm.

**Comment by kasymovga** [comment]
![devel20230514005147-00](https://github.com/kasymovga/rexuiz/assets/9973821/84c7fa58-e2ec-4744-9541-286c733659ee)
More extended dialog for profiles added in developing version (will become available trough update in several days).
I don't planning restore all original mutators and their dialog, because it's hard to support.
